# Generated by Django 5.1.6 on 2025-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_group_end_date_remove_group_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
