# Generated by Django 5.1.6 on 2025-03-14 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_student_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='price',
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.homework')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
        ),
    ]
