# Generated by Django 5.1.6 on 2025-03-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_homework_price_baho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='baho',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.grouphomework'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.group')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
        ),
    ]
